In [1]:
import numpy as np

In [2]:
print (np.zeros((3,3,3),dtype=np.int))

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [3]:
# N=(input().split( ))
# x=int(N[0])
# y=int(N[1])
# z=int(N[2])
# print(x,y,z)

1 2  3
1 2 3


In [7]:
import numpy
N=(input().split( ))

M=[]
for i in range(len(N)):
    M.append(int(N[i]))
M=tuple(M)
print (numpy.zeros(M,dtype=numpy.int))
print (numpy.ones(M,dtype=numpy.int))






1 2 3
[[[0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]]]


In [30]:
W=(input().split())
w1=int(W[0])
w2=int(W[1])
w3=0
a=numpy.eye(w1, w2, w3)
print(a)

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
s1=' 1 2'


ValueError: invalid literal for int() with base 10: ' 1 2'

In [32]:
import numpy
print(str(numpy.eye(*map(int,input().split()))).replace('1',' 1').replace('0',' 0'))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
