In [1]:
import numpy as np 
from numpy import pi

In [11]:
np.random.seed(0)

In [41]:
np.random.seed(0)
v=np.random.uniform(low=0, high=1, size=(400,4096))
v

array([[0.5488135 , 0.71518937, 0.60276338, ..., 0.59982458, 0.2280461 ,
        0.41678175],
       [0.31829425, 0.64285395, 0.43103467, ..., 0.81186436, 0.58873947,
        0.56606423],
       [0.49735062, 0.09631765, 0.68749721, ..., 0.28712698, 0.60400281,
        0.7720906 ],
       ...,
       [0.02005684, 0.91261562, 0.25578782, ..., 0.06113735, 0.05087707,
        0.71631662],
       [0.0465463 , 0.33758621, 0.22329929, ..., 0.39242263, 0.61497174,
        0.92195694],
       [0.14159476, 0.00931506, 0.31019302, ..., 0.5299475 , 0.10183901,
        0.98492805]])

In [51]:
np.mean(v,axis=1)

array([0.49863194, 0.4919352 , 0.49585631, 0.4910055 , 0.50320538,
       0.49834516, 0.49910456, 0.50071549, 0.49814129, 0.50205067,
       0.49628689, 0.49760605, 0.50592411, 0.49696962, 0.49711677,
       0.49985007, 0.50203253, 0.50118196, 0.50067662, 0.49756578,
       0.5015315 , 0.50463248, 0.50153798, 0.50639511, 0.50402889,
       0.50459662, 0.49920207, 0.50623843, 0.50394659, 0.50170567,
       0.50239991, 0.49659178, 0.50147853, 0.50078379, 0.50063756,
       0.5038686 , 0.49514477, 0.50230466, 0.49773879, 0.49912088,
       0.50966274, 0.50213721, 0.50308665, 0.50421458, 0.50900041,
       0.50437645, 0.49665457, 0.50285294, 0.50393549, 0.5042038 ,
       0.49864784, 0.49787906, 0.4968333 , 0.49823908, 0.50469649,
       0.4967105 , 0.49433041, 0.50332187, 0.49816824, 0.49846141,
       0.48998771, 0.49855248, 0.49244939, 0.49583877, 0.49660362,
       0.49906281, 0.49839091, 0.51153793, 0.48668635, 0.49258215,
       0.49996859, 0.50076052, 0.50007288, 0.49130031, 0.49379

In [50]:
mean=np.zeros((400,))
for i in range(400):
    for j in range(4096):
        mean[i]=mean[i]+v[i,j]
        
mean=mean/4096
mean

array([0.49863194, 0.4919352 , 0.49585631, 0.4910055 , 0.50320538,
       0.49834516, 0.49910456, 0.50071549, 0.49814129, 0.50205067,
       0.49628689, 0.49760605, 0.50592411, 0.49696962, 0.49711677,
       0.49985007, 0.50203253, 0.50118196, 0.50067662, 0.49756578,
       0.5015315 , 0.50463248, 0.50153798, 0.50639511, 0.50402889,
       0.50459662, 0.49920207, 0.50623843, 0.50394659, 0.50170567,
       0.50239991, 0.49659178, 0.50147853, 0.50078379, 0.50063756,
       0.5038686 , 0.49514477, 0.50230466, 0.49773879, 0.49912088,
       0.50966274, 0.50213721, 0.50308665, 0.50421458, 0.50900041,
       0.50437645, 0.49665457, 0.50285294, 0.50393549, 0.5042038 ,
       0.49864784, 0.49787906, 0.4968333 , 0.49823908, 0.50469649,
       0.4967105 , 0.49433041, 0.50332187, 0.49816824, 0.49846141,
       0.48998771, 0.49855248, 0.49244939, 0.49583877, 0.49660362,
       0.49906281, 0.49839091, 0.51153793, 0.48668635, 0.49258215,
       0.49996859, 0.50076052, 0.50007288, 0.49130031, 0.49379

In [44]:
 np.mean(v, axis = 0)

array([0.5373768 , 0.5122041 , 0.51288414, ..., 0.48311859, 0.49965658,
       0.47453913])

In [6]:
A=np.arange(12).reshape(3, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
#the number of axes (dimensions) of the array.
A.ndim

2

In [17]:
A.shape

(3, 4)

In [20]:
A.size

12

In [21]:

A.dtype 

dtype('int32')

In [22]:
# one elements size 
A.itemsize

4

In [24]:
type(A)

numpy.ndarray

In [27]:
A.data

In [28]:
#Array Creation 
#a = np.array(1,2,3,4) wrong
a = np.array([1,2,3,4])

In [30]:
#complex 
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [31]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
 np.ones( (2,3,4), dtype=np.int16 )  

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [33]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [37]:
np.linspace( 0, 2, 9 ) # slice 0 to 2 into 9 part 


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [39]:
x = np.linspace( 0, 2*pi, 100 )
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [41]:
f = np.sin(x)
max(f)

0.9998741276738751

In [42]:
 print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [44]:
a = np.array( [20,30,40,50] )

In [45]:
b = np.arange( 4 )

In [47]:
c = a-b
c 

array([20, 29, 38, 47])

In [48]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [49]:
a<35

array([ True,  True, False, False])

### Basic Operation

In [50]:
A = np.array( [[1,1],[0,1]] )

In [51]:
B = np.array( [[2,0],[3,4]])

In [52]:
A * B   # elementwise product

array([[2, 0],
       [0, 4]])

In [53]:
A @ B  # matrix product

array([[5, 4],
       [3, 4]])