In [4]:
'Nik'.join(list(['Alice',
'Bob',"hill"]))

'AliceNikBobNikhill'

In [14]:
x={'Alice' : 18}
y={'Bob' : 27, 'Ann' : 22}
z = {**x,**y}
z

{'Alice': 18, 'Bob': 27, 'Ann': 22}

In [17]:
x.update(y)


In [18]:
list1=[1,2,4,5,12,1,2,3]
seen,duplicate=set(),set()

for i in list1:
    if i in seen:
        duplicate.add(i)
    seen.add(i)
print(duplicate)

{1, 2}


In [26]:
def is_anagram(s1, s2):
    #or set(s1)==set(s2) 
    return len(set(s1))==len(set(s1).intersection(set(s2)))
print(is_anagram("elvis", "lives")) 

True


In [91]:
l1=[1,2,3,4]
l2=[1,2,3,6,4,8]

In [92]:
l2.reverse()
print(l2)

[8, 4, 6, 3, 2, 1]


In [48]:
def intersect(lst1, lst2):
    res, lst2_copy = [], lst2[:]
    for el in lst1:
        if el in lst2_copy:
            res.append(el)
            lst2_copy.remove(el)
    return res
intersect(l1,l2)

[1, 2, 3, 4]

In [52]:
def qsort(L):
    if L == []: 
        return []
    return qsort([x for x in L[1:] if x< L[0]]) + L[0:1] +qsort([x for x in L[1:] if x>=L[0]])
lst = [44, 33, 22,78]
qsort(lst)

[22, 33, 44, 78]

In [46]:
set(l1) | set(l2)

{1, 2, 3, 4, 6}

In [63]:
def get_permutations(w):
    if len(w) <= 1:
        return set(w)
    smaller = get_permutations(w[1:])
    perms = set()
    print(smaller)
    for x in smaller:
     
        for pos in range(0, len(x)+1):
            perm = x[:pos] + w[0] + x[pos:]
            perms.add(perm)
    return perms
print(get_permutations("nik"))

{'k'}
{'ik', 'ki'}
{'ink', 'ikn', 'nik', 'kin', 'nki', 'kni'}


In [64]:
import numpy as np

In [85]:
np.split(np.arange(0,99,3),3)


[array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30]),
 array([33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63]),
 array([66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96])]

In [87]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [86]:
print(np.cumsum(np.arange(5)))

[ 0  1  3  6 10]


In [93]:
"""foo'bar"""

"foo'bar"

In [95]:
"foo\'bar"

"foo'bar"

In [96]:
'foo\'bar'

"foo'bar"

In [2]:
def fact(n):
    if n==1:
        return 1
    else:
        return n*(n-1)

In [7]:
fact(9)

72

In [10]:
def DecimalToBinary(num):
    if num >= 1:
        DecimalToBinary(num // 3)
    print(num % 3, end = '')

In [13]:
n=91
def fun(n):
    if n>=0 or n>=1:
            print("yes")
    else:
        fun(n//3)
        

011011

In [23]:
n = 152
res = 0
while(n > 0):
    digit = n % 10
    res=(res*10)+digit
    n=n//10

In [24]:
print(res)

251


In [ ]:
while temp > 0:
    digit = temp % 10
    sum += digit ** 3
    temp //= 10