In [44]:
import numpy as np
np.__version__
import cv2

## basic code 

In [4]:
arr_row=np.array([1,2,3])
arr_row.shape

(3,)

In [5]:
arr_col=np.array([[1],[2],[3]])
arr_col.shape

(3, 1)

## 2d array

In [9]:
arr_2d=np.array([[[1,2,3],[1,4,5]]])
arr_2d.shape

(1, 2, 3)

## default value

In [15]:
x=np.zeros((3,3),dtype="int")  #uint8

In [17]:
x=np.ones((3,3),dtype="float")
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
x=np.full((3,4),fill_value=4)
x

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [25]:
x=np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
x=np.arange(0,10,2)
x

array([0, 2, 4, 6, 8])

In [35]:
x=np.linspace(0,9,11)
x

array([0. , 0.9, 1.8, 2.7, 3.6, 4.5, 5.4, 6.3, 7.2, 8.1, 9. ])

## random generate

In [38]:
x=np.random.rand(3,5)*255
x

array([[ 13.04470665, 143.69989363,  20.75157213,  58.50932804,
         43.92452742],
       [186.27889961,  57.62554545,  88.31159334, 167.59412119,
         65.96839496],
       [ 55.6657388 ,  43.66388204, 252.59830962, 199.59921611,
         97.09682917]])

In [41]:
x=np.random.randint(5,size=(3,3))
x

array([[3, 1, 2],
       [2, 4, 3],
       [2, 0, 2]])

In [57]:
np.linalg.eig(x)[::-1]

(array([[-0.45865136, -0.49758251,  0.08445292],
        [-0.85684191, -0.39936552, -0.90117927],
        [-0.23550132,  0.77001223,  0.42513954]]),
 array([5.89510652, 0.70759841, 2.39729507]))

In [60]:
x=np.random.rand(3,5)
x.size
x

array([[0.49607444, 0.54614819, 0.18386904, 0.51872052, 0.18516684],
       [0.34797176, 0.30154729, 0.80364472, 0.43660442, 0.44310961],
       [0.78274976, 0.72828389, 0.87967348, 0.29923848, 0.11178718]])

In [66]:
x=np.random.randint(high=10,low=8,size=(6,6))
x=x.astype(float)
x

array([[8., 9., 8., 9., 8., 9.],
       [8., 9., 9., 9., 9., 8.],
       [8., 8., 9., 8., 9., 9.],
       [9., 9., 8., 8., 9., 8.],
       [8., 8., 9., 8., 8., 9.],
       [9., 8., 8., 8., 8., 9.]])

In [68]:
x1=np.array([[1,2,3],[3,4,5]])
x2=np.array([[1,2,3],[3,4,5]])
x_f=x1+x2
x_f

array([[ 2,  4,  6],
       [ 6,  8, 10]])

## indexing

In [26]:
x=np.array([[1,20,3],[3,4,5]])
print(x)
np.amax(x,axis=1)

[[ 1 20  3]
 [ 3  4  5]]


array([20,  5])

In [37]:
x=np.array([[1,20,3],[3,4,5]])
print(x[0:2,:])

[[ 1 20  3]
 [ 3  4  5]]


In [40]:
x[::-1]

array([[ 3,  4,  5],
       [ 1, 20,  3]])

In [43]:
x.reshape(3,2)

array([[ 1, 20],
       [ 3,  3],
       [ 4,  5]])

In [ ]:
x=np.zeros((500,500))
x[:,:]=0
x[100:200,200:300]=255

cv2.imshow("img",x)