In [9]:
import numpy as np 
import matplotlib.pyplot as plt

In [3]:
A=np.array([[1,2],[4,3]])

In [4]:
k,B=np.linalg.eig(A)

In [31]:
B

array([[1, 1],
       [0, 8]])

In [7]:
np.linalg.eig(B)

(array([1., 2.]),
 array([[1.        , 0.70710678],
        [0.        , 0.70710678]]))

In [ ]:
#import numpy as np
import matplotlib.pyplot as plt
M = np.array([[1,1],[-2,2],[4,-7]])

print("vector:1")
print(M[0,:])
# print("vector:2")
# print(M[1,:])
rows,cols = M.T.shape
print(cols)

for i,l in enumerate(range(0,cols)):
    print("Iteration: {}-{}".format(i,l))
    print("vector:{}".format(i))
    print(M[i,:])
    v1 = [0,0],[M[i,0],M[i,1]]
    # v1 = [M[i,0]],[M[i,1]]
    print(v1)
    plt.figure(i)
    plt.plot(v1)
    plt.show()

In [8]:
%matplotlib qt 

In [17]:
import matplotlib.artist as Df


In [42]:
A=np.array([[1,2],[4,3]])
B =np.array([[1,1],[0,8]])

In [67]:

fig = plt.figure()
ax = fig.add_subplot(1, 2, 1)
x,y = np.meshgrid(np.linspace(-5,5,8),np.linspace(-5,5,8))
u=np.array([[1,2],[4,3]])


ax.quiver(x,y,u)
plt.grid()
ax= fig.add_subplot(1,2,2)
ax.quiver(x,y,headwidth=3.0,headlength=3.0)
fig.subplots_adjust(hspace=1.5, wspace=0.4)
plt.grid()
plt.show()

In [36]:
xx, yy = np.meshgrid(xvalues, yvalues)

In [37]:
xx

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])