In [3]:
import numpy as np 
import matplotlib.pyplot as plt
import numpy.linalg as la 

In [3]:
A=np.array([[1,2],[4,3]])

In [4]:
k,B=np.linalg.eig(A)

In [31]:
B

array([[1, 1],
       [0, 8]])

In [7]:
np.linalg.eig(B)

(array([1., 2.]),
 array([[1.        , 0.70710678],
        [0.        , 0.70710678]]))

In [ ]:
#import numpy as np
import matplotlib.pyplot as plt
M = np.array([[1,1],[-2,2],[4,-7]])

print("vector:1")
print(M[0,:])
# print("vector:2")
# print(M[1,:])
rows,cols = M.T.shape
print(cols)

for i,l in enumerate(range(0,cols)):
    print("Iteration: {}-{}".format(i,l))
    print("vector:{}".format(i))
    print(M[i,:])
    v1 = [0,0],[M[i,0],M[i,1]]
    # v1 = [M[i,0]],[M[i,1]]
    print(v1)
    plt.figure(i)
    plt.plot(v1)
    plt.show()

In [8]:
%matplotlib qt 

In [17]:
import matplotlib.artist as Df


In [42]:
A=np.array([[1,2],[4,3]])
B =np.array([[1,1],[0,8]])

In [67]:

fig = plt.figure()
ax = fig.add_subplot(1, 2, 1)
x,y = np.meshgrid(np.linspace(-5,5,8),np.linspace(-5,5,8))
u=np.array([[1,2],[4,3]])


ax.quiver(x,y,u)
plt.grid()
ax= fig.add_subplot(1,2,2)
ax.quiver(x,y,headwidth=3.0,headlength=3.0)
fig.subplots_adjust(hspace=1.5, wspace=0.4)
plt.grid()
plt.show()

In [36]:
xx, yy = np.meshgrid(xvalues, yvalues)

In [37]:
xx

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [15]:
a=np.array([[0,1/2,0,0],[1/3,0,0,1/2],[1/3,0,0,1/2],[1/3,1/2,1,0]])

In [16]:
a

array([[0.        , 0.5       , 0.        , 0.        ],
       [0.33333333, 0.        , 0.        , 0.5       ],
       [0.33333333, 0.        , 0.        , 0.5       ],
       [0.33333333, 0.5       , 1.        , 0.        ]])

In [17]:
b=np.array([1/4,1/4,1/4,1/4])
b

array([0.25, 0.25, 0.25, 0.25])

In [18]:
eigen_vect=np.linalg.eig(a)
eigen_vect 

(array([ 1.00000000e+00, -9.17517095e-02, -9.08248290e-01,  5.88174157e-17]),
 array([[-2.22988244e-01, -8.25340062e-01,  2.62323812e-01,
         -8.01783726e-01],
        [-4.45976488e-01,  1.51452723e-01, -4.76510307e-01,
         -1.04906215e-16],
        [-4.45976488e-01,  1.51452723e-01, -4.76510307e-01,
          2.67261242e-01],
        [-7.43294146e-01,  5.22434615e-01,  6.90696802e-01,
          5.34522484e-01]]))

In [19]:
dia=np.diag(a)

In [20]:
a_inv=np.linalg.inv(a)

LinAlgError: Singular matrix

In [21]:
np.linalg.det(a)

0.0

In [28]:
b=np.array([[1,2,3],[1,4,5],[4,8,7]])

In [29]:
evals,eigv=la.eig(b)

In [30]:
evals

array([13.08773064,  0.48563159, -1.57336223])

In [31]:
lam=np.diag(evals)

In [32]:
lam

array([[13.08773064,  0.        ,  0.        ],
       [ 0.        ,  0.48563159,  0.        ],
       [ 0.        ,  0.        , -1.57336223]])

In [33]:
eigv_inv=la.inv(eigv)

In [52]:

B=eigv @ (lam)**100 @ eigv_inv
B

array([[4.02891380e+110, 9.51129502e+110, 9.79728245e+110],
       [6.85901696e+110, 1.61924869e+111, 1.66793657e+111],
       [1.16607970e+111, 2.75283328e+111, 2.83560600e+111]])

In [51]:

(b)**100

array([[          1,           0,  -818408495],
       [          1,           0, -1971132175],
       [          0,           0,  1027218017]], dtype=int32)