In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import h5py
import scipy
from PIL import Image
from scipy import ndimage
from lr_utils import load_dataset

%matplotlib inline

## sigmoid  
s=1+(1/1+e^(-z))

In [3]:
def sigmoid(z):

    score=1/(1+np.e**(-z))

    return score




In [8]:
print("sigmoid([0, 2]) = " + str(sigmoid(np.array([0,2]))))

sigmoid([0, 2]) = [0.5        0.88079708]


In [9]:
sigmoid(np.array([1,2]))

array([0.73105858, 0.88079708])

## Initilize dimensions
z=w*x^(i)+b

In [15]:
def initialize_with_zeros(dim):
    """
    This function creates a vector of zerX=np.array([[1,1]])os of shape (dim, 1) for w and initializes b to 0.
    
    Argument:
    dim -- size of the w vector we want (or number of parameters in this case)
    
    Returns:
    w -- initialized vector of shape (dim, 1)
    b -- initialized scalar (corresponds to the bias)
    """

    w=np.zeros((dim,1))
    b=0

    assert (w.shape==(dim,1))
    assert(isinstance(b, float) or isinstance(b, int))

    return w,b


    


    

In [16]:
initialize_with_zeros(4)

(array([[0.],
        [0.],
        [0.],
        [0.]]),
 0)

<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mi>A</mi>
  <mo>=</mo>
  <mi>&#x03C3;<!-- σ --></mi>
  <mo stretchy="false">(</mo>
  <msup>
    <mi>w</mi>
    <mi>T</mi>
  </msup>
  <mi>X</mi>
  <mo>+</mo>
  <mi>b</mi>
  <mo stretchy="false">)</mo>
  <mo>=</mo>
  <mo stretchy="false">(</mo>
  <msup>
    <mi>a</mi>
    <mrow>
      <mo stretchy="false">(</mo>
      <mn>1</mn>
      <mo stretchy="false">)</mo>
    </mrow>
  </msup>
  <mo>,</mo>
  <msup>
    <mi>a</mi>
    <mrow>
      <mo stretchy="false">(</mo>
      <mn>2</mn>
      <mo stretchy="false">)</mo>
    </mrow>
  </msup>
  <mo>,</mo>
  <mo>.</mo>
  <mo>.</mo>
  <mo>.</mo>
  <mo>,</mo>
  <msup>
    <mi>a</mi>
    <mrow>
      <mo stretchy="false">(</mo>
      <mi>m</mi>
      <mo>&#x2212;<!-- − --></mo>
      <mn>1</mn>
      <mo stretchy="false">)</mo>
    </mrow>
  </msup>
  <mo>,</mo>
  <msup>
    <mi>a</mi>
    <mrow>
      <mo stretchy="false">(</mo>
      <mi>m</mi>
      <mo stretchy="false">)</mo>
    </mrow>
  </msup>
  <mo stretchy="false">)</mo>
</math>


<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mtable displaystyle="true">
    <mlabeledtr>
      <mtd id="mjx-eqn-3">
        <mtext>(3)</mtext>
      </mtd>
      <mtd>
              <mi class="MJX-tex-caligraphic" mathvariant="script">L</mi>
        <mo stretchy="false">(</mo>
        <msup>
          <mi>a</mi>
          <mrow>
            <mo stretchy="false">(</mo>
            <mi>i</mi>
            <mo stretchy="false">)</mo>
          </mrow>
        </msup>
        <mo>,</mo>
        <msup>
          <mi>y</mi>
          <mrow>
            <mo stretchy="false">(</mo>
            <mi>i</mi>
            <mo stretchy="false">)</mo>
          </mrow>
        </msup>
        <mo stretchy="false">)</mo>
        <mo>=</mo>
        <mo>&#x2212;<!-- − --></mo>
        <msup>
          <mi>y</mi>
          <mrow>
            <mo stretchy="false">(</mo>
            <mi>i</mi>
            <mo stretchy="false">)</mo>
          </mrow>
        </msup>
        <mi>log</mi>
        <mo>&#x2061;<!-- ⁡ --></mo>
        <mo stretchy="false">(</mo>
        <msup>
          <mi>a</mi>
          <mrow>
            <mo stretchy="false">(</mo>
            <mi>i</mi>
            <mo stretchy="false">)</mo>
          </mrow>
        </msup>
        <mo stretchy="false">)</mo>
        <mo>&#x2212;<!-- − --></mo>
        <mo stretchy="false">(</mo>
        <mn>1</mn>
        <mo>&#x2212;<!-- − --></mo>
        <msup>
          <mi>y</mi>
          <mrow>
            <mo stretchy="false">(</mo>
            <mi>i</mi>
            <mo stretchy="false">)</mo>
          </mrow>
        </msup>
        <mo stretchy="false">)</mo>
        <mi>log</mi>
        <mo>&#x2061;<!-- ⁡ --></mo>
        <mo stretchy="false">(</mo>
        <mn>1</mn>
        <mo>&#x2212;<!-- − --></mo>
        <msup>
          <mi>a</mi>
          <mrow>
            <mo stretchy="false">(</mo>
            <mi>i</mi>
            <mo stretchy="false">)</mo>
          </mrow>
        </msup>
        <mo stretchy="false">)</mo>
      </mtd>
    </mlabeledtr>
  </mtable>
</math>


In [ ]:
pip install nbconvert

$$
J = -\frac{1}{m}\sum_{i=1}^{m}y^{(i)}\log(a^{(i)})+(1-y^{(i)})\log(1-a^{(i)})
$$

In [43]:
def propagate(w, b, X, Y):
    
    m=X.shape[1]
    
    A=sigmoid(np.dot(w.T,X)+b)

    cost = (np.sum((-np.log(A)*Y)+(-np.log(1-A)*(1-Y))))/m

    dw = (np.dot(X,(A-Y).T))/m
    db = (np.sum(A-Y))/m


    assert(dw.shape == w.shape)
    assert(db.dtype == float)
    cost = np.squeeze(cost)
    assert(cost.shape == ())
    
    grads = {"dw": dw,
             "db": db}
    
    return grads, cost

In [44]:
w=np.array([[1.],[2.]])
b=1
X=np.array([[1.,2.,-1.],[3.,4.,-3.2]])
y=np.array([1,0,1])

In [51]:
def optimize(w, b, X, Y, num_iterations, learning_rate, print_cost = False):
    costs = []
    for i in range(num_iterations):

        grads,cost=propagate(w,b,X,Y)

        dw = grads["dw"]
        db = grads["db"]

        w=w-(learning_rate)*dw
        b=b-(learning_rate)*db

        if i % 100 == 0:
            costs.append(cost)
        
        # Print the cost every 100 training iterations
        if print_cost and i % 100 == 0:
            print ("Cost after iteration %i: %f" %(i, cost))
        
    params = {"w": w,
              "b": b}
    
    grads = {"dw": dw,
             "db": db}

    return params, grads, costs


In [52]:
w=np.array([[1.],[2.]])
b=1
X=np.array([[1.,2.,-1.],[3.,4.,-3.2]])
Y=np.array([1,0,1])

In [55]:
result=optimize(w, b, X, Y, 1000, 0.0001, print_cost = True)

Cost after iteration 0: 5.800671
Cost after iteration 100: 5.733191
Cost after iteration 200: 5.665723
Cost after iteration 300: 5.598266
Cost after iteration 400: 5.530822
Cost after iteration 500: 5.463393
Cost after iteration 600: 5.395978
Cost after iteration 700: 5.328581
Cost after iteration 800: 5.261201
Cost after iteration 900: 5.193841


In [66]:
result[0]['w'].shape


(2, 1)

In [74]:
def predict(X,result):
    m = X.shape[1]
    Y_prediction = np.zeros((1,m))
    w=result[0]['w']
    b=result[0]['b']
    w = w.reshape(X.shape[0], 1)

    A=sigmoid(np.dot(w.T,X)+b)

    print(A)


    



In [77]:
X = np.array([[1.,-1.1,-3.2],[1.2,2.,0.1]])

In [79]:
X.shape

(2, 3)

In [78]:
predict(X,result)

[[0.98223224 0.97154288 0.15389421]]
